### ISSUE TITLE
issue in post 

### ISSUE THREAD

**Issue by lsnovich** [Aaron-Gor/API-Docs#17]
please change
The customer can order one or more beef or a veggie burger. The size can be 300 or 400 gr. The customer has the option to specify how the burger is cooked: medium rare, medium or well-done The customer has the option to choose the bun type: white or whole wheat. The customer can choose the type of topping for the burger: lettuce, tomoato, onion, or no topping. The customer can choose which condiment to have with the burger: ketchup, BBQ sauce, mushroom sauce, or no condiment.

to
The customer can order one or more beef or veggie burgers. The size can be 300 or 400 g. The customer has the option to specify how the burger is cooked: medium rare, medium, or well-done The customer has the option to choose the bun type: white or whole wheat. The customer can choose the type of topping for the burger: lettuce, tomoato, onion, or no topping. The customer can choose which condiment to have with the burger: ketchup, BBQ sauce, mushroom sauce, or no condiment.

**Comment by Aaron-Gor** [comment]
@lsnovich Fixed #18
